Fix panel component disjointed heading
alphagov/govuk_publishing_components pull request #1660
Opened 2020-08-24 16:10 UTC by danacotoran

## What
On the panel component, move the optional prepended text and appended text into the same block as the `text` for the heading.

## Why

The prepended text, heading text, and appended text on the panel component should be in the same block.

The issue with the prepended and appended text being outside the heading element is that they provide context for the heading. Screen reader users might be confused by the incomplete heading and not understand it out of context when they are navigating a page according to its headings.

### Example of the issue
The panel text on https://www.gov.uk/bank-holidays for each next bank holiday is disjointed. It should be in the same block level element.
```
  <div>
    The next bank holiday in England and Wales is
  </div>
  <h2>
    31 August
  </h2>
  <div>
      Summer bank holiday
  </div>
```

https://trello.com/c/9eXF6FRF

2020-08-24 16:54 UTC, owenatgov approved these changes
Looks awwwright to me

2020-08-25 07:17 UTC, maxgds commented
This is a good step forward on fixing the accessibility but I question whether this should be a h2 at all. It isn't a heading as there is no content tied to it and my guess is that historically it was styled as one because it looked good visually. Given that by its nature what appears here is always going to be in a panel it can't really ever be sentence summary of the subsequent paragraphs of content which is the aim of a heading, and small snippets of text surrounding it are kind of orphaned and meaningless by themselves. I suggest getting a second opinion (@injms ?) in case I'm an outlier on this suggestion, but have a look around for examples of the component in use (I usually do a github search for this) to see if this holds true across the board. If removing it wouldn't leave chunks of content headerless then switch out the markup. Consider a screenreader might be trying to read blocks of content at once, so div, heading, div is going to be very disjointed still. I'd suggest a paragraph with a span around what is currently the h2.

2020-08-25 07:21 UTC, maxgds requested changes
Please see the comment I left, I think this might want a bit more tweaking.

2020-08-26 13:17 UTC, maxgds approved these changes
As discussed, maybe worth re-examining the use case in Bank Holidays later, but the component seems sound like this, so approving.

2020-08-26 13:34 UTC, merged