Add legacy `govspeak` class alongside gem govspeak
alphagov/govuk_publishing_components pull request #2044
Opened 2021-05-04 11:00 UTC by injms

## What

Adds the `govspeak` class alongside the `gem-c-govspeak` class - this makes sure that the `govspeak` has the same output as `gem-c-govspeak` for minimal additional CSS.

## Why

There are many many many places where the older `govspeak` class is used on elements that wrap around content, rather than `gem-c-govspeak`. This class comes as part of the content from the content store (eg [in `details.body` in the cabinet office content][1].

Adding the legacy class as a fix is easier and safer that changing the myriad of places where this is added - around 7K places across alphagov[2]).

[1]: https://www.gov.uk/api/content/government/organisations/cabinet-office
[2]: https://github.com/search?q=org%3Aalphagov+%27%3Cdiv+class%3D%22govspeak%22%3E%27&type=Code&ref=advsearch&l=&l=

## Visual Changes

None.

2021-05-04 15:57 UTC, maxgds requested changes
Whilst I appreciate the comment "Legacy class name" it doesn't describe to me why it needs to be there. Could we expand on that in the comment, mentioning that it's sometimes contained in content items?

2021-05-04 15:57 UTC, maxgds requested changes
Whilst I appreciate the comment "Legacy class name" it doesn't describe to me why it needs to be there. Could we expand on that in the comment, mentioning that it's sometimes contained in content items?

2021-05-04 18:19 UTC, injms commented
> Whilst I appreciate the comment "Legacy class name" it doesn't describe to me why it needs to be there. Could we expand on that in the comment, mentioning that it's sometimes contained in content items?

Good point - I've added a (hopefully) better comment explaining why it's unfortunately needed.

2021-05-05 07:08 UTC, maxgds approved these changes

2021-05-06 10:06 UTC, merged