Adding ID to list item
alphagov/govuk_publishing_components pull request #2059
Opened 2021-05-11 12:58 UTC by chris-gds

## What?

Extending the list component to allow a user to pass an ID to a list item, should no custom ID be provide one will be generated.

## Why?

Whilst [converting](https://github.com/alphagov/whitehall/pull/6091) an element to use the [list component](http://localhost:3212/component-guide/list) (on Whitehall) this resulted in a testing error due to a missing ID. Current iteration of this gem component does not provide an option to generate an ID or provide a custom one. 

This extension aims to resolve this and provide these options for future list component use.

## Visual Changes
None however screenshots for Context attached

![Screenshot 2021-05-11 at 13 54 35](https://user-images.githubusercontent.com/71266765/117818457-88672e00-b260-11eb-8113-444d28275917.png)

![Screenshot 2021-05-11 at 13 54 45](https://user-images.githubusercontent.com/71266765/117818449-869d6a80-b260-11eb-8dee-ededfaac7712.png)

Anything else?

Raising a draft for feedback

2021-06-14 13:23 UTC, injms commented on app/views/govuk_publishing_components/components/_list.html.erb
> +      <% end %>
Am I reading this right - would this put the same `id` on each of the list items in the list?

2021-06-14 13:35 UTC, injms commented on app/views/govuk_publishing_components/components/_list.html.erb
> +      <% end %>
Just checked, and the same `id` is added to different list elements.

2021-06-14 13:35 UTC, injms requested changes
There shouldn't be multiple `id`s that are the same on the page - each list item needs a unique `id` attribute, or no `id` attribute.

2021-06-22 08:36 UTC, chris-gds commented
> There shouldn't be multiple `id`s that are the same on the page - each list item needs a unique `id` attribute, or no `id` attribute.

Agreed. In this context this PR needs to be adjusted for a unique ID attribute.  
However as this requirement is currently only required in Whitehall (I've not seen other apps need this feature) currently investigating why a unique ID is being used and if it can be removed to avoid this need for this update.

2022-05-20 09:05 UTC, andysellick commented
@maxgds this PR's been sitting around for a while - is this feature still a requirement or can this PR be closed?

2022-05-23 09:55 UTC, maxgds commented
I think we found a workaround for this - certainly this work isn't on our radar at the moment. I'll close this but bear in in mind if the issue resurfaces.

2022-05-23 09:55 UTC, closed without merging