Add analytics tags to super navigation header
alphagov/govuk_publishing_components pull request #2246
Opened 2021-08-06 13:34 UTC by chao-xian

## What

## Why

## Visual Changes

2021-08-06 14:04 UTC, owenatgov commented
This PR was originally put together by myself in https://github.com/alphagov/govuk_publishing_components/pull/2244, however, because it was branched off of a new defunct branch, we created this new one as rebasing back to master was too complex and this is time-sensitive work. Therefore, @chao-xian can review this if they want.

2021-08-06 22:42 UTC, chao-xian commented
I've tidied some errant deleting of entries from the CHANGELOG. New entries in master weren't included as the cherry-pick didn't account for that commit being before master being updated, and I didn't rebase it.

2021-08-06 23:03 UTC, chao-xian commented
@owenatgov this LGTM but I can't approve it... 😬

2021-08-07 15:30 UTC, owenatgov approved these changes
Approving on behalf of Kelvin based on his comment above. A bit wild west but this is quite a complex launch we're doing.

2021-08-09 09:13 UTC, injms commented on spec/javascripts/components/layout-super-navigation-header-spec.js
>          })
This skipped test can be removed; it's been updated with:

https://github.com/alphagov/govuk_publishing_components/blob/d4a897b33089817b476fec645cf11f43d2e5bc93/spec/javascripts/components/layout-super-navigation-header-spec.js#L738-L740

```suggestion
```

2021-08-09 09:14 UTC, injms commented on spec/javascripts/components/layout-super-navigation-header-spec.js
> +        xit('updates the button’s state', function () {
This skipped test can also be removed as it's been updated: 

https://github.com/alphagov/govuk_publishing_components/blob/d4a897b33089817b476fec645cf11f43d2e5bc93/spec/javascripts/components/layout-super-navigation-header-spec.js#L772-L778

2021-08-09 09:15 UTC, injms requested changes
A couple of tests need removing, then this is good to go.

2021-08-09 10:57 UTC, injms commented on app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
>              <a class="gem-c-layout-super-navigation-header__navigation-item-link" href="<%= link[:href] %>">
Does this link need anything extra so that clicks on it can be tracked?

2021-08-09 11:00 UTC, injms commented on app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
>              <a class="gem-c-layout-super-navigation-header__navigation-item-link" href="<%= link[:href] %>">
Ignore me, there's no requirement for these links to be tracked. Plus they're hidden when JavaScript is enabled, which would make tracking clicks on them impossible.

2021-08-09 11:00 UTC, injms reviewed
Super!

2021-08-09 11:01 UTC, injms approved these changes

2021-08-09 11:08 UTC, merged