Strip postcodes from more document types
alphagov/govuk_publishing_components pull request #2720
Opened 2022-04-07 09:40 UTC by MartinJJones

## What
The documents types listed below will now include the `<meta name="govuk:static-analytics:strip-postcodes" content="true">` meta tag.

- transaction
- local_transaction
- place
- special_route

This will ensure that pages with these document types, have the postcodes stripped and replaced with "[postcode]" in pii.js

## Why
To stop postcode data from being sent to Google Analytics.

2022-04-08 14:25 UTC, jon-kirwan requested changes
Thanks Martin. Looking good to me. I just have one small change request to squash the commit history down in to a single commit

2022-04-11 09:32 UTC, MartinJJones commented
Thanks @jon-kirwan, I have squashed the commit history down in to a single commit as requested.

2022-04-11 10:19 UTC, 1pretz1 reviewed
Change looks good 👍 We should probably add a test as I can see that there are two already for `finder` and `smart_answer` document types: 
https://github.com/alphagov/govuk_publishing_components/blob/main/spec/components/meta_tags_spec.rb#L369-L377.

Maybe we could refactor them a single test for each doc type and create a constant for `formats_that_might_include_postcodes` in the `MetaTags` class and use it in the spec file so we don’t have to maintain two lists.

We'll also need to update the [CHANGELOG](https://github.com/alphagov/govuk_publishing_components/blob/main/CHANGELOG.md) to specify an `unreleased` version, before bumping the version.

2022-04-11 15:34 UTC, 1pretz1 approved these changes
Looks great, nice work! 🍏

2022-04-13 08:56 UTC, merged