Use section for emergency banner
alphagov/govuk_publishing_components pull request #2973
Opened 2022-09-20 14:03 UTC by patrickpatrickpatrick

## What

Small adjustments to the template of emergency banner for accessibility reasons.

## Why

When the emergency banner was deployed on GOV.UK, some changes were made based on the feedback from an accessibility specialist. These changes involved removing the role attribute from the parent div and changing the element of the parent div to a section. This is to avoid any accidental duplication of roles on any page of GOV.UK. In accordance with this change, the aria-label has been changed to aria-labelledby instead.

2022-09-26 15:45 UTC, hannalaakso approved these changes
I've compared the outputted markup against the banner that was deployed on production and the `section` tag and `aria-labelledby` linked with `id` match what was published there 👍

2022-09-26 15:52 UTC, hannalaakso requested changes
Apologies for revoking the approval but I've just realised that it'd be good to add a test for the `aria-labelledby` to check it matches the `id` on the heading.

2022-09-30 11:36 UTC, patrickpatrickpatrick commented
have added that test

2022-10-03 12:10 UTC, hannalaakso approved these changes
LGTM 👍

2022-10-03 14:26 UTC, merged