Add GA4 tracking to the super breadcrumb
alphagov/govuk_publishing_components pull request #3272
Opened 2023-02-23 11:59 UTC by JamesCGDS

## What
Adds tracking to the super breadcrumb.

## Why
Part of the GA4 migration.

## Visual Changes
N/A

Trello card: https://trello.com/c/AM5JCKEd/430-add-tracking-to-super-breadcrumbs

2023-02-24 08:08 UTC, JamesCGDS commented on app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
> +  <%= tag.div class: classes, data: { module: "gem-track-click ga4-link-tracker" } do %>
Yeah good point, sorry wasn't focusing - I'll make that change 👍

2023-02-24 17:45 UTC, JamesCGDS commented
Hi @gclssvglx - I've had to make some changes to the Ruby code (details in the PR description, happy to explain further if I haven't made sense!) and was wondering if you'd be able to also give this a look?

2023-02-27 09:02 UTC, gclssvglx approved these changes
Nice one @JamesCGDS 👍

2023-02-27 10:00 UTC, andysellick requested changes
Suddenly thought - can this be documented in the component guide?

2023-03-06 15:53 UTC, andysellick approved these changes
🚀

2023-03-06 15:55 UTC, merged