Update error summary to use component wrapper helper
alphagov/govuk_publishing_components pull request #3308
Opened 2023-03-17 16:22 UTC by jon-kirwan

## What
Update error summary to use component wrapper helper

## Why

Resolves an issue whereby the data-module attribute value is overwritten if you pass in a data-module attribute. 

## Visual Changes
None

## Anything else

2023-03-17 16:35 UTC, jon-kirwan commented
> @jon-kirwan so great to see someone else implementing this! If you have time, can you add an entry to the [audit spreadsheet](https://docs.google.com/spreadsheets/d/1J-0IPyr2ycPuw1IWOIoX0o9Tk9nF35D0DJdsj_ylLQE/edit?pli=1#gid=1458513074)?

Sure no problem - now updated! 👍

2023-03-20 16:37 UTC, AshGDS requested changes
Looks good, but I think you need to add `uses_component_wrapper_helper: true` to the `.yml` doc?

2023-03-20 16:48 UTC, jon-kirwan commented
> Looks good, but I think you need to add `uses_component_wrapper_helper: true` to the `.yml` doc?

Good spot! Thank you. I've now updated the yaml docs to include the line

2023-03-21 09:22 UTC, andysellick approved these changes
Great to see this being implemented in other components. In theory you could remove the example from the component guide that demonstrates data attributes, now that it's included as part of the 'standard' options.

2023-03-21 10:13 UTC, AshGDS approved these changes

2023-03-21 12:20 UTC, merged