Add GA4 debugging assistance
alphagov/govuk_publishing_components pull request #3388
Opened 2023-05-10 14:19 UTC by andysellick

## What
- outputs details of analytics data pushed to the datalayer, to aid with debugging analytics events on any system particularly between pages
- to use, set the variable in the console: window.GOVUK.analyticsGa4.showDebug = true, then set the console to preserve log, then do a thing to trigger an event

## Why
I've been finding that the browser tools for debugging analytics events aren't 100% reliable, and this will help in some situation.

## Visual Changes
None.

2023-05-10 16:03 UTC, AshGDS requested changes
Thanks for adding this :+1: - had a small question/change request which might work

2023-05-10 16:11 UTC, AshGDS commented
Actually, what I suggested above is a bad idea, since people who aren't working on GA4 would then have a bunch of `console.log`s that they don't want!

2023-05-11 08:41 UTC, andysellick commented on app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
Ahhh that's much better, thanks! Knew there should be a nicer way of doing this, but hadn't found it. Updated.

2023-05-11 08:56 UTC, AshGDS approved these changes
All good - needs a standardx run (and maybe a CHANGELOG rebase as I just merged something!)

2023-05-11 09:13 UTC, merged