Make YoutubeLinkEnhancement URL parsing more robust.
alphagov/govuk_publishing_components pull request #4003
Opened 2024-04-30 13:41 UTC by sengi

[URL API] `searchParams` works [pretty much everywhere](https://caniuse.com/?search=searchparams) since around 2017, which includes [all the user agents we support](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices). It also considerably simplifies the code and makes the intent much clearer.

(We have to avoid static `canParse()` though, because Samsung Internet is weird.)

Resolves https://github.com/alphagov/govuk_publishing_components/security/code-scanning/1.

[URL API]: https://developer.mozilla.org/en-US/docs/Web/API/URL

No visual or functional change intended.

2024-05-01 08:45 UTC, andysellick requested changes
@sengi looks like a sensible change except that `includes` and (haven't confirmed this yet but fairly sure) `searchParams` aren't supported by older browsers like IE. While we don't support those browsers we do want to ensure they have a reasonable experience of GOV.UK and this change would probably cause all of the JS to break suddenly.

We're currently working on an RFC to remove JS support for IE11, can this PR wait until then? https://github.com/alphagov/govuk-rfcs/pull/171

2024-05-01 11:08 UTC, sengi commented
Ah ok, TIL we still de facto support IE11 😅

If you're sure we need to continue to support embedded YT videos in IE11 for the time being then I'm happy to stick this on the back burner until you're ready to drop IE.

I'll make it draft for now anyway.

2024-05-01 11:39 UTC, sengi commented
Actually wouldn't be just dropping support for adding/editing YT embeds in the content management tools in IE? Is this library even used in the public-facing frontends?

2024-05-01 11:44 UTC, sengi commented
Even so, I'm not sure this would affect anything public-facing because it's in the govspeak library and surely we're not doing the govspeak->html transform on the client? 🤔

2024-05-02 08:08 UTC, andysellick commented
> Even so, I'm not sure this would affect anything public-facing because it's in the govspeak library and surely we're not doing the govspeak->html transform on the client? 🤔

Correct, we're not doing the govspeak->html transform on the client, but we are running this JS on that output in the client to convert links to videos into embedded videos. See [this page](https://www.gov.uk/guidance/help-and-support-for-self-assessment) for an example - if JS is disabled the embedded videos show simply as links to Youtube.

2024-05-02 08:37 UTC, sengi commented
Aha thanks! Super helpful example ❤️

2024-06-18 11:45 UTC, sengi commented
I'm guessing this depends on #4000 — does that sound right?

2024-09-04 10:54 UTC, andysellick approved these changes

2024-09-04 10:54 UTC, merged